version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - run: npm i
      - run: nmp run lint
  
  test:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  
  analyze:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - run: npm audit
  
workflows:
  app-workflow:
    - build
    - test:
        requires:
          - build
    - analyze:
        requires:
          - test
  
